"""The vendored tree: where it lives, its pin, and the build preconditions over it.

The vendored ``frappe_docker`` tree lives at ``src/cairn/vendored/frappe_docker`` —
*inside* the cairn package itself (BR-VEND-001) — so it ships in the wheel the same way
every other package file does, and every path in this module is resolved relative to
cairn's own installed location, never by searching the filesystem for a project root.
That is what makes these checks work identically in a development checkout and in a
``pip install``.

``ventwig`` is a **fetch-time-only** tool. The only two operations that touch it are
``status``/``sync`` below, thin wrappers a human runs deliberately from a checkout
(BR-VEND-009) to pull a new upstream pin. Once a sync lands, cairn never invokes ventwig
again: the build preconditions (``assert_clean``/``assert_no_nested_git``/
``assert_build_inputs``) work entirely from the vendored tree and its companion
``frappe_docker.pin.toml`` — no ``ventwig`` import, no subprocess, no dependency on it
being installed. That pin file is regenerated by ``sync()`` from ventwig's own
``.ventwig.lock`` and is the immutability anchor from then on (BR-VEND-003, BR-VEND-005).

``cairn doctor`` runs the same three preconditions ahead of time (BR-CLI-007).
"""

from __future__ import annotations

import importlib.util
import shutil
import subprocess
import sys
import tempfile
import tomllib
from pathlib import Path

from .errors import (
    ProjectRootNotFoundError,
    VendorDriftError,
    VendorInputsMissingError,
    VendorToolError,
)
from .project import read_vendor_sources

GIT_DIR_NAME = ".git"

#: The vendored source that supplies the image build inputs (BR-VEND-006).
FRAPPE_DOCKER_SOURCE = "frappe_docker"

#: Where the vendored tree and its pin live, relative to cairn's own installed location —
#: not searched for, so this resolves identically in a checkout and in a wheel.
VENDORED_DIR = Path(__file__).resolve().parent / "vendored"
FRAPPE_DOCKER_DIR = VENDORED_DIR / FRAPPE_DOCKER_SOURCE
PIN_FILE = VENDORED_DIR / f"{FRAPPE_DOCKER_SOURCE}.pin.toml"

#: ventwig's own lock file — read only by `sync()`, to refresh PIN_FILE after a fetch.
LOCK_NAME = ".ventwig.lock"

#: The custom-image Containerfile cairn builds with, relative to that source (ADR-004).
CUSTOM_CONTAINERFILE = "images/custom/Containerfile"


# --- ventwig wrappers (fetch-time only) --------------------------------------


def status(root: Path, source: str | None = None) -> int:
    """Run ``ventwig status`` (streaming its output) and return its exit code (BR-CLI-006)."""
    return _run(_args("status", source), root, capture=False).returncode


def sync(root: Path, source: str | None = None) -> int:
    """Run ``ventwig sync``, then refresh ``PIN_FILE`` from the lock it just wrote.

    The refresh only runs after a successful sync, and only touches the pin file — the
    vendored tree itself is exactly what ventwig wrote (BR-CLI-006).
    """
    result = _run(_args("sync", source), root, capture=False)
    if result.returncode == 0:
        _refresh_pin_file(root, source or FRAPPE_DOCKER_SOURCE)
    return result.returncode


def _refresh_pin_file(root: Path, source_name: str) -> None:
    """Rewrite ``PIN_FILE`` from ``root``'s ``.ventwig.lock``, for ``source_name``.

    Silently does nothing if the lock has no entry for *source_name* — leaves the
    previous pin in place rather than blanking it over an unrelated sync.
    """
    try:
        sources = read_vendor_sources(root)
    except ProjectRootNotFoundError:
        return
    ref = next((s.ref or "" for s in sources if s.name == source_name), "")

    try:
        with (root / LOCK_NAME).open("rb") as handle:
            locked = tomllib.load(handle).get(source_name)
    except (OSError, tomllib.TOMLDecodeError):
        locked = None
    if not locked:
        return

    PIN_FILE.write_text(
        "# Generated by `cairn vendor sync` from .ventwig.lock. Do not hand-edit.\n"
        f'ref = "{ref}"\n'
        f'commit = "{locked.get("synced_commit", "")}"\n'
        f'synced_tree = "{locked.get("synced_tree", "")}"\n'
        f'synced_at = "{locked.get("synced_at", "")}"\n',
        encoding="utf-8",
    )


def read_pin() -> dict[str, str]:
    """Return the vendored upstream's recorded pin (ref, commit, synced_tree, synced_at).

    Missing or unparseable degrades to an empty dict rather than raising — callers that
    need the pin to exist (`assert_clean`) check for that themselves; provenance
    (`build.provenance_labels`) is fine recording empty strings (BR-VEND-005 is what
    actually guarantees integrity, already enforced before labels are built).
    """
    try:
        with PIN_FILE.open("rb") as handle:
            data = tomllib.load(handle)
    except (OSError, tomllib.TOMLDecodeError):
        return {}
    return {k: str(v) for k, v in data.items()}


# --- build preconditions (no ventwig involved) -------------------------------


def assert_clean() -> None:
    """Raise :class:`VendorDriftError` unless the vendored tree matches its recorded pin.

    The build precondition: drift is a **hard stop** with no override (BR-VEND-005).
    Recomputes the tree's content hash the same way ventwig computed it at sync time (a
    scratch git repo, `git write-tree`) and compares it to `PIN_FILE`'s `synced_tree` —
    which catches any difference between what's on disk and what was actually fetched,
    hand-edit or otherwise, without needing ventwig itself.
    """
    pin = read_pin()
    expected = pin.get("synced_tree", "")
    if not expected:
        raise VendorDriftError(
            f"{FRAPPE_DOCKER_SOURCE} has no recorded pin ({PIN_FILE} is missing or empty); "
            f"refusing to build. Run `cairn vendor sync` from a checkout."
        )

    current = _tree_hash(FRAPPE_DOCKER_DIR)
    if current != expected:
        raise VendorDriftError(
            f"The vendored {FRAPPE_DOCKER_SOURCE} tree has drifted from its recorded pin "
            f"(expected tree {expected[:12]}, found {current[:12]}). This usually means a "
            f"hand-edit — the vendored tree must never be modified. Restore it with "
            f"`cairn vendor sync`, or revert your changes."
        )


def assert_no_nested_git() -> None:
    """Raise :class:`VendorDriftError` if the vendored tree contains a nested ``.git``.

    The vendored tree must be plain committed files (BR-VEND-007).
    """
    nested = FRAPPE_DOCKER_DIR / GIT_DIR_NAME
    if nested.exists():
        raise VendorDriftError(
            f"Vendored source '{FRAPPE_DOCKER_SOURCE}' contains a nested {GIT_DIR_NAME} "
            f"({nested}); the vendored tree must be plain committed files."
        )


def assert_build_inputs() -> None:
    """Raise :class:`VendorInputsMissingError` unless the vendored tree carries every
    build input the custom Containerfile needs (BR-VEND-006).

    The required set is derived from the Containerfile itself — each path it copies from
    the build context — so it stays correct across upstream bumps rather than encoding a
    list that silently rots.
    """
    containerfile = FRAPPE_DOCKER_DIR / CUSTOM_CONTAINERFILE
    if not containerfile.is_file():
        raise VendorInputsMissingError(
            f"Vendored source '{FRAPPE_DOCKER_SOURCE}' is missing {CUSTOM_CONTAINERFILE} "
            f"(expected at {containerfile}). Restore it with `cairn vendor sync`."
        )

    missing = [
        path for path in _context_copies(containerfile) if not _resolves(FRAPPE_DOCKER_DIR, path)
    ]
    if missing:
        raise VendorInputsMissingError(
            f"{CUSTOM_CONTAINERFILE} copies build inputs that are absent from the vendored "
            f"tree: {', '.join(sorted(missing))}. Restore them with `cairn vendor sync`."
        )


def containerfile_path() -> Path:
    """Return the path to the vendored custom Containerfile (`ADR-004`)."""
    return FRAPPE_DOCKER_DIR / CUSTOM_CONTAINERFILE


def build_context() -> Path:
    """Return the build context — the vendored source root, per `BR-BUILD-009`."""
    return FRAPPE_DOCKER_DIR


def containerfile_arg_defaults(containerfile: Path) -> dict[str, str]:
    """Return the ``ARG NAME=default`` pairs declared by *containerfile*.

    `BR-BUILD-010` requires recording **effective** build args, "including Containerfile
    defaults where unset" — so the defaults are read from the artifact itself rather than
    transcribed, and a vendored-pin bump that moves a default is picked up automatically.
    ``ARG`` lines without a default are skipped: they contribute no value.
    """
    defaults: dict[str, str] = {}
    for line in containerfile.read_text(encoding="utf-8").splitlines():
        tokens = line.strip().split(maxsplit=1)
        if len(tokens) != 2 or tokens[0].upper() != "ARG" or "=" not in tokens[1]:
            continue
        name, _, value = tokens[1].partition("=")
        defaults[name.strip()] = value.strip().strip('"').strip("'")
    return defaults


def _context_copies(containerfile: Path) -> list[str]:
    """Return the build-context paths the Containerfile's ``COPY`` instructions read.

    ``COPY --from=<stage>`` lines are skipped: their sources come from an earlier build
    stage, not from the vendored tree.
    """
    paths: list[str] = []
    for line in containerfile.read_text(encoding="utf-8").splitlines():
        tokens = line.strip().split()
        if not tokens or tokens[0].upper() != "COPY":
            continue
        flags = [t for t in tokens[1:] if t.startswith("--")]
        operands = [t for t in tokens[1:] if not t.startswith("--")]
        if any(flag.startswith("--from=") for flag in flags) or len(operands) < 2:
            continue
        paths.extend(operands[:-1])  # the last operand is the in-image destination
    return paths


def _resolves(source_root: Path, path: str) -> bool:
    """Report whether *path* (possibly a glob) exists under the vendored source root."""
    if any(ch in path for ch in "*?["):
        return any(source_root.glob(path))
    return (source_root / path).exists()


def _tree_hash(path: Path) -> str:
    """Return a git tree hash of *path*'s contents, the same way ventwig computes one.

    Uses a scratch git repo so nothing outside *path* is touched. Needs only the `git`
    binary cairn already requires unconditionally (`doctor.check_git`) — never `ventwig`.
    """
    try:
        with tempfile.TemporaryDirectory() as tmpdir:
            repo = Path(tmpdir)
            _git(["init", "-q", str(repo)])
            shutil.copytree(path, repo, dirs_exist_ok=True, ignore=shutil.ignore_patterns(".git"))
            _git(["add", "-A"], cwd=repo)
            return _git(["write-tree"], cwd=repo)
    except FileNotFoundError as exc:
        raise VendorDriftError(
            "git is required to verify the vendored tree but is not installed."
        ) from exc


def _git(args: list[str], cwd: Path | None = None) -> str:
    result = subprocess.run(
        ["git", *args], cwd=cwd, capture_output=True, text=True, check=False
    )
    if result.returncode != 0:
        raise VendorDriftError(f"`git {' '.join(args)}` failed:\n{result.stderr.strip()}")
    return result.stdout.strip()


# --- ventwig plumbing (fetch-time only) --------------------------------------


def _args(subcommand: str, source: str | None) -> list[str]:
    return [subcommand, source] if source else [subcommand]


def _run(args: list[str], root: Path, *, capture: bool) -> subprocess.CompletedProcess[str]:
    _require_ventwig()
    return subprocess.run(
        [sys.executable, "-m", "ventwig", *args],
        cwd=root,
        capture_output=capture,
        text=True,
        check=False,
    )


def _require_ventwig() -> None:
    if importlib.util.find_spec("ventwig") is None:
        raise VendorToolError(
            "ventwig is required for vendoring commands but is not installed. "
            "Install it with: pip install ventwig"
        )
